
const AppConstants = {
  // Canvas
  ADD_ELEMENT_TO_CANVAS: 'ADD_ELEMENT_TO_CANVAS',
  CLEAR_CANVAS: 'CLEAR_CANVAS',
  // Components
  MAKE_COMPONENT_ACTIVE: 'MAKE_COMPONENT_ACTIVE',
  DELETE_COMPONENT: 'DELETE_COMPONENT'
}

export default AppConstants;
